### ISSUE TITLE
Default to opening files in mutable mode, special option for immutable files

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#419]
One of the original ideas behind Datasette was that serving immutable data makes everything way easier. Two examples: You don't have to worry about SQLite concurrency and you can bundle the database inside a Docker container and deploy it to immutable hosting. See [The interesting ideas in Datasette](https://simonwillison.net/2018/Oct/4/datasette-ideas/) for more on this.

I'm beginning to see a much stronger case for being able to serve mutable data as well.

SQLite is actually perfectly capable of handling reads against a database that is also being written to, even if the writes are coming from another process. https://www.sqlite.org/wal.htm

There are all kinds of interesting use-cases which Datasette is currently unsuitable for due to its insistence on immutable databases. Some examples:

* Continually run Datasette against a SQLite database updated by another process, e.g. Firefox bookmarks
* Projects where a cron runs every X minutes and writes new entries gathered from other sources to SQLite
* Tail a log file, write those log updates to a SQLite file, view recent log entries in Datasette

This is also relevant to #417, Datasette Library.

**Comment by simonw** [comment]
Thinking about this further: I think I may have made a mistake establishing "immutable" as the default mode for databases opened by Datasette.

What would it look like if files were NOT opened in immutable mode by default?

**Comment by simonw** [comment]
Some problems to solve:

* Right now Datasette assumes it can always show the count of rows in a table, because this has been pre-calculated. If a database is mutable the pre-calculation trick no longer works, and for giant tables a `select count(*) from X` query can be expensive to run. Maybe we set a time limit on these? If time limit expires show "many rows"?
* Maintaining a content hash of the table no longer makes sense if it is changing (though interestingly there's a `.sha3sum` built-in SQLite CLI command which takes a hash of the content and stays the same even through vacuum runs). Without that we need a different mechanism for calculating table colours. It also means that we can't do the special dbname-hash URL trick (see #418) at all if the database is opened as mutable.

**Comment by simonw** [comment]
Could I persist the last calculated count for a table and somehow detect if that table has been changed in any way by another process, hence invalidating the cached count (and potentially scheduling a new count)?

**Comment by simonw** [comment]
So the differences here are:

* For immutable databases we calculate content hash and table counts; mutable databases we do not
* Immutable databasse open with `file:{}?immutable=1`, mutable databases open with `file:{}?mode=ro`
* Anywhere that shows a table count now needs to call a new method which knows to run `count(*)` with a timeout for mutable databases, read from the precalculated counts for immutable databases
* The url-hash option should no longer be available at all for mutable databases

**Comment by simonw** [comment]
And a really important difference: the whole model of caching inspect data no longer works for mutable files, because another process might make a change to the database schema (adding a new table for example).

So everywhere that uses `self.ds.inspect()` right now will have to change to calling a routine which knows the difference between mutable and immutable databases and queries for live schema data for mutables while using a cache for immutables.

**Comment by simonw** [comment]
I've added the `-i` option, so this now works:

    datasette -i fixtures.db

This feature is incomplete though. Some extra changes I need to make:

- [ ] The `?_hash=1` and `--config hash_urls:1` options (introduced in #418) should only work for immutable databases
- [ ] Needs more robust test coverage
- [ ] Would be useful if there was a debug screen that could show which databases were mounted as mutable v.s. immutable - maybe a `/-/databases` or `/-/connections` page?
- [ ] Need to rework how `.inspect()` works, see #420 
- [ ] Documentation is needed #421

 particular,

**Comment by simonw** [comment]
I just closed #420 - all of the places in the codebase that were using `.inspect()` should have been eliminated.

**Comment by russss** [comment]
Are you planning on removing inspect entirely? 

I didn't spot this work before I started on datasette-geo, but ironically I think it has a use case which really needs the inspect functionality (or some replacement). 

Datasette-geo uses it to store the bounding box of all the geographic features in the table. This is needed when rendering the map because it avoids having to send loads of tile requests for areas which are empty. 

Even with relatively small datasets, calculating the bounding box seems to take around 5 seconds, so I don't think it's really feasible to do this on page load.

One possible fix would be to do this on startup, and then in a thread which watches the database for changes.

**Comment by simonw** [comment]
@russss sorry I only just spotted your comment here.

I think I have an alternative suggestion for what you need to do here. It sounds to me like you need to calculate a specific piece of information against a specific database. Instead of doing this in inspect, how about having a separate tool which runs this once against the database file and writes the result into a database file there?

I've been thinking about this pattern a bit as part of the sqlite-utils work I've been doing. It's already something that's needed for SQLite FTS support - it's no good just creating a FTS index, you have to populate it as well. In sqlite-utils world you do that like this: https://sqlite-utils.readthedocs.io/en/latest/cli.html#configuring-full-text-search

    $ sqlite-utils enable-fts mydb.db documents title summary

But then later if you've inserted new records you have to call this:

    $ sqlite-utils populate-fts mydb.db documents title summary

So one option here could be for `datasette-geo` to know to look for a special `datasette_geo_bounding_box` database table and, if it's missing, to calculate at runtime (probably once on startup and then cache it).

Another option: Datasette now has an option to open a database file in "immutable" mode, using `datasette -i mydatabase.db`. When you do that we calculate counts on startup - and we'll also be able to load counts from the `inspect-data.json` file (that's pretty much all that will be in there). I'm open to making this available as a plugin hook - all kinds of optimizations could be run against these `-i` databases. It would essentially be what we have with inspect today but just for databases opened in that specific mode.

**Comment by simonw** [comment]
This is done bar the documentation, which is tracked in #421
